name: Compile LaTeX Documents

on:
  workflow_run:
    workflows:
      - Build LaTeX Docker Image
    types:
      - completed
  push:
    paths:
      - 'logic_v1/*.tex'
      - 'logic_v2/*.tex'
      - '.github/workflows/compile-latex.yml' # Trigger on changes to this workflow file

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/latex-build:latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Compile LaTeX documents in logic_v1
      - name: Compile LaTeX in logic_v1
        run: |
          cd logic_v1
          mkdir -p output
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error *.tex
          for file in *.pdf; do mv "$file" "output/logic_v1_$file"; done

      # Compile LaTeX documents in logic_v2
      - name: Compile LaTeX in logic_v2
        run: |
          cd logic_v2
          mkdir -p output
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error *.tex
          for file in *.pdf; do mv "$file" "output/logic_v2_$file"; done

      # Create GitHub release with PDFs
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            logic_v1/output/*.pdf
            logic_v2/output/*.pdf
          tag_name: pdf-${{ github.sha }}
          name: PDF Build ${{ github.sha }}
          body: |
            Automated PDF build from commit ${{ github.sha }}
            Organized PDFs:
            - logic_v1/output/
            - logic_v2/output/
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
