name: Compile LaTeX Documents

on:
  workflow_run:
    workflows:
      - Build LaTeX Docker Image
    types:
      - completed

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/latex-build:latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Compile LaTeX documents in logic_v1
      - name: Compile LaTeX in logic_v1
        run: |
          cd logic_v1
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error *.tex

      # Compile LaTeX documents in logic_v2
      - name: Compile LaTeX in logic_v2
        run: |
          cd logic_v2
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error *.tex

      # Create GitHub release with PDFs
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            logic_v1/*.pdf
            logic_v2/*.pdf
          tag_name: pdf-${{ github.sha }}
          name: PDF Build ${{ github.sha }}
          body: Automated PDF build from commit ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
